config/routes.rb
Rails.application.routes.draw do
  get '/sign_up' => 'users#new', as: 'sign_up'
  get '/sign_in' => 'sessions#new', as: 'sign_in'
  delete '/sign_out' => 'sessions#destroy', as: 'sign_out'

  root 'home#welcome'

  resources :users
  resources :sessions
  resources :password_resets
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    
    # Ensures an authentication token is generated for each User instance made
    before_create { generate_token(:authentication_token) }

    # Allows the method to work with multiple columns for other processes
    def generate_token(column)
        begin
            # ActiveSupport generates a random string
            self[column] = SecureRandom.urlsafe_base64
        # Token is unique by ensuring no other user exists with that same token
        end while User.exists?(column => self[column])
    end

    def send_password_reset
        # Generates an authentication reset token
        generate_token(:password_reset_token)
        # Sets the current time to be checked against for expiration of reset link later on
        self.password_reset_sent_at = Time.zone.now
        # Saves the User model with a password reset token and time
        save!
        # Send an email to User
        UserMailer.password_reset(self).deliver
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private

  # Defines the current user and it's cached so that it's only requested once
  def current_user
    @current_user ||= User.find_by_authentication_token!(cookies[:authentication_token]) if cookies[:authentication_token]
  end
  # Helper method allows this method to be used in views
  helper_method :current_user

  # Makes it so that a user must be signed in before perfoming an action if this is in a before action for a controller
  def authenticate_user
    redirect_to sign_in_url, alert: "You must be signed in to view this page" if current_user.nil?
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def welcome
    end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  def new
  end

  def create
    # Searches for a user with the email entered in the password reset form
    user = User.find_by_email(params[:email])
    # Email will be sent regardless if a user is found in the database so it becomes much more secure
    user.send_password_reset if user
    redirect_to root_url, notice: "Password Reset Sent"
  end
  
  def edit
    # Searches for a user with the token generated as the id in the url
    @user = User.find_by_password_reset_token!(params[:id])
  end

  def update
    # Searches for a user with the token generated as the id in the url
    @user = User.find_by_password_reset_token!(params[:id])
    # If the link has been out for more than 10 minutes then do not update the password in the database
    if @user.password_reset_sent_at < 10.minutes.ago
      redirect_to new_password_reset_path, alert: "Password reset link has expired"
    # If the password was successfully changed then redirect to the home page
    elsif @user.update_attributes(password_reset_params)
      redirect_to root_url, notice: "Password successfully reset"
    # Other errors just render the edit page
    else
      render :edit
    end
  end

  private

  def password_reset_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    # Find the current user using the email provided
    user = User.find_by_email(params[:email])
    # Authenticate is a method provided by has_secure_password, checks against a user's bcrypt password
    if user && user.authenticate(params[:password])
      # Sets user authentication token so that it can be used in future requests. If remember me is set then maintain that authentication token in a cookie
      if params[:remember_me]
        cookies.permanent[:authentication_token] = user.authentication_token
      # Otherwise only remember the cookie for that session
      else
        cookies[:authentication_token] = user.authentication_token
      end
      redirect_to root_url, notice: "Successfully Logged In"
    else
      # Pops up a message on the current window
      flash.now.alert = "Email or password is invalid"
      render "new"
    end
  end

  def destroy
    # Delete cookie of authentication token so the user is logged out
    cookies.delete(:authentication_token)
    redirect_to root_url, notice: "Successfully Logged Out"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    # Creates a new User instance and displays the sign up form
    def new
        @user = User.new
    end

    # Create action that saves the User instance to the database
    def create
        @user = User.new(user_params)
        # If the User instance was successfully saved then redirect to home page and display notice
        if @user.save
            # Set authentication token cookie so that the User is automatically signed in after signing up
            cookies[:authentication_token] = @user.:authentication_token
            redirect_to root_url, notice: "Thank you for signing up."
        # If the User instance was not saved in the database then redisplay the sign up form
        else
            render :new
        end
    end

    private

    # Paramaters that are allowed to pass through
    def user_params
        params.require(:user).permit(:email, :password, :password_confirmation, :authentication_token, :password_reset_token)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/welcome.html.erb
<h1>Welcome to Authentication Practice</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AuthPractice</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div class="user_header">
        <% if current_user %>
          Welcome, <%= current_user.email %>
          <%= link_to "Sign Out", sign_out_path(current_user), method: :delete %>
        <% else %>
          <%= link_to "Sign Up", sign_up_path %> or
          <%= link_to "Sign In", sign_in_path %>
        <% end %>
      </div>
      <%= yield %>
    </div>
  </body>
</html>

app/views/password_resets/edit.html.erb
<h1>Reset Password</h1>

<!-- Uses model: over url: because it associates with the User model. Specifies a url because it does not use the one relating to users -->
<%= form_with(model: @user, url: password_reset_path(params[:id])) do |form|  %>
    <!-- If there are any errors -->
    <% if @user.errors.any? %>
        <div>
            <h3>Form is invalid</h3>
            <!-- Find all errors and display them -->
            <% @user.errors.full_messages.each do |message| %>
                <p><%= message %></p>
            <% end %>
        </div>
    <% end  %>

    <div class="field">
        <%= form.label :password %><br />
        <%= form.password_field :password, id: :password %>
    </div>

    <div class="field">
        <%= form.label :password_confirmation %><br />
        <%= form.password_field :password_confirmation, id: :password_confirmation %>
    </div>

    <div class="actions"><%= form.submit "Reset Password" %></div>
<% end %>

app/views/password_resets/new.html.erb
<h1>Reset Password</h1>

<!-- Uses url: over model: because it does not associate with a model, method: :post uses the create action in the controller -->
<%= form_with(url: password_resets_path, method: :post) do |form| %>

    <div class="field">
        <%= form.label :email %><br />
        <!-- Passes email parameters to be used in the controller -->
        <%= text_field_tag :email, params[:email] %>
    </div>

    <div class="actions"><%= form.submit "Reset Password" %></div>

<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<!-- Uses model: over url: because it associates with the User model -->
<%= form_with(model: @user, local: true) do |form|  %>
    <!-- If there are any errors -->
    <% if @user.errors.any? %>
        <div>
            <h3>Form is invalid</h3>
            <!-- Find all errors and display them -->
            <% @user.errors.full_messages.each do |message| %>
                <p><%= message %></p>
            <% end %>
        </div>
    <% end  %>

    <div class="field">
        <%= form.label :email %><br />
        <%= form.text_field :email, id: :email %>
    </div>

    <div class="field">
        <%= form.label :password %><br />
        <%= form.password_field :password, id: :password %>
    </div>

    <div class="field">
        <%= form.label :password_confirmation %><br />
        <%= form.password_field :password_confirmation, id: :password_confirmation %>
    </div>

    <div class="actions"><%= form.submit "Sign Up" %></div>
<% end %>